/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigConfig {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<Box<models::ConfigApp>>,
    #[serde(rename = "cache", skip_serializing_if = "Option::is_none")]
    pub cache: Option<Box<models::CachesProvider>>,
    #[serde(rename = "cli", skip_serializing_if = "Option::is_none")]
    pub cli: Option<Box<models::AppCli>>,
    #[serde(rename = "cloud", skip_serializing_if = "Option::is_none")]
    pub cloud: Option<Box<models::ConfigCloud>>,
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<Box<models::DatabasesProvider>>,
    #[serde(rename = "httpClient", skip_serializing_if = "Option::is_none")]
    pub http_client: Option<Box<models::HttplibClient>>,
    #[serde(rename = "httpServer", skip_serializing_if = "Option::is_none")]
    pub http_server: Option<Box<models::HttplibServer>>,
    #[serde(rename = "jsonnet", skip_serializing_if = "Option::is_none")]
    pub jsonnet: Option<Box<models::JsonnetJsonnet>>,
    #[serde(rename = "oidc", skip_serializing_if = "Option::is_none")]
    pub oidc: Option<std::collections::HashMap<String, models::OidcClientIssuer>>,
    #[serde(rename = "smtp", skip_serializing_if = "Option::is_none")]
    pub smtp: Option<Box<models::NotifySmtp>>,
    #[serde(rename = "webPush", skip_serializing_if = "Option::is_none")]
    pub web_push: Option<Box<models::NotifyWebPush>>,
}

impl ConfigConfig {
    pub fn new() -> ConfigConfig {
        ConfigConfig {
            app: None,
            cache: None,
            cli: None,
            cloud: None,
            database: None,
            http_client: None,
            http_server: None,
            jsonnet: None,
            oidc: None,
            smtp: None,
            web_push: None,
        }
    }
}

