/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigApp {
    #[serde(rename = "adminEmailAddresses", skip_serializing_if = "Option::is_none")]
    pub admin_email_addresses: Option<Vec<String>>,
    #[serde(rename = "adminTrustedCIDRs", skip_serializing_if = "Option::is_none")]
    pub admin_trusted_cidrs: Option<Vec<String>>,
    #[serde(rename = "baseURL", skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[serde(rename = "cacheControl", skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<String>,
    #[serde(rename = "cloudDevKey", skip_serializing_if = "Option::is_none")]
    pub cloud_dev_key: Option<bool>,
    #[serde(rename = "cloudEndpoint", skip_serializing_if = "Option::is_none")]
    pub cloud_endpoint: Option<String>,
    /// nolint: tagliatelle
    #[serde(rename = "cloudJWT", skip_serializing_if = "Option::is_none")]
    pub cloud_jwt: Option<String>,
    /// nolint: tagliatelle
    #[serde(rename = "cloudPrivateKey", skip_serializing_if = "Option::is_none")]
    pub cloud_private_key: Option<Box<models::CryptolibKeyCryptolibKeyProviderPrivate>>,
    #[serde(rename = "contactFeedback", skip_serializing_if = "Option::is_none")]
    pub contact_feedback: Option<String>,
    #[serde(rename = "contactSupport", skip_serializing_if = "Option::is_none")]
    pub contact_support: Option<String>,
    #[serde(rename = "counterTimeZone", skip_serializing_if = "Option::is_none")]
    pub counter_time_zone: Option<String>,
    /// TODO remove 2026-02-27  Deprecated: use EnableDemo
    #[serde(rename = "demo", skip_serializing_if = "Option::is_none")]
    pub demo: Option<bool>,
    #[serde(rename = "disableNotifications", skip_serializing_if = "Option::is_none")]
    pub disable_notifications: Option<bool>,
    #[serde(rename = "disableSignup", skip_serializing_if = "Option::is_none")]
    pub disable_signup: Option<bool>,
    #[serde(rename = "disableTasks", skip_serializing_if = "Option::is_none")]
    pub disable_tasks: Option<bool>,
    #[serde(rename = "disableWebConfig", skip_serializing_if = "Option::is_none")]
    pub disable_web_config: Option<bool>,
    #[serde(rename = "enableCustomAPI", skip_serializing_if = "Option::is_none")]
    pub enable_custom_api: Option<bool>,
    #[serde(rename = "enableDemo", skip_serializing_if = "Option::is_none")]
    pub enable_demo: Option<bool>,
    #[serde(rename = "ignorePaymentFailures", skip_serializing_if = "Option::is_none")]
    pub ignore_payment_failures: Option<bool>,
    #[serde(rename = "keepCalendarEventDays", skip_serializing_if = "Option::is_none")]
    pub keep_calendar_event_days: Option<i32>,
    #[serde(rename = "keepCookMealPlanDays", skip_serializing_if = "Option::is_none")]
    pub keep_cook_meal_plan_days: Option<i32>,
    #[serde(rename = "keepDeletedDays", skip_serializing_if = "Option::is_none")]
    pub keep_deleted_days: Option<i32>,
    #[serde(rename = "keepExpiredAuthHouseholdDays", skip_serializing_if = "Option::is_none")]
    pub keep_expired_auth_household_days: Option<i32>,
    #[serde(rename = "keepHealthLogItemDays", skip_serializing_if = "Option::is_none")]
    pub keep_health_log_item_days: Option<i32>,
    #[serde(rename = "keepHealthLogMetricMonths", skip_serializing_if = "Option::is_none")]
    pub keep_health_log_metric_months: Option<i32>,
    #[serde(rename = "keepInactiveAuthAccountDays", skip_serializing_if = "Option::is_none")]
    pub keep_inactive_auth_account_days: Option<i32>,
    #[serde(rename = "keepNotesPageVersions", skip_serializing_if = "Option::is_none")]
    pub keep_notes_page_versions: Option<i32>,
    #[serde(rename = "keepPlanTaskDays", skip_serializing_if = "Option::is_none")]
    pub keep_plan_task_days: Option<i32>,
    #[serde(rename = "motd", skip_serializing_if = "Option::is_none")]
    pub motd: Option<String>,
    #[serde(rename = "privateKeys", skip_serializing_if = "Option::is_none")]
    pub private_keys: Option<Vec<models::CryptolibKeyCryptolibKeyProviderPrivate>>,
    #[serde(rename = "proxyAddress", skip_serializing_if = "Option::is_none")]
    pub proxy_address: Option<String>,
    #[serde(rename = "proxyHeaderEmail", skip_serializing_if = "Option::is_none")]
    pub proxy_header_email: Option<String>,
    #[serde(rename = "proxyHeaderName", skip_serializing_if = "Option::is_none")]
    pub proxy_header_name: Option<String>,
    #[serde(rename = "rollupBudgetMonthCategoriesMonths", skip_serializing_if = "Option::is_none")]
    pub rollup_budget_month_categories_months: Option<i32>,
    #[serde(rename = "rollupBudgetTransactionsBalanceMonths", skip_serializing_if = "Option::is_none")]
    pub rollup_budget_transactions_balance_months: Option<i32>,
    #[serde(rename = "rollupBudgetTransactionsSummaryMonths", skip_serializing_if = "Option::is_none")]
    pub rollup_budget_transactions_summary_months: Option<i32>,
    #[serde(rename = "rollupHealthLogMetricsDays", skip_serializing_if = "Option::is_none")]
    pub rollup_health_log_metrics_days: Option<i32>,
    #[serde(rename = "rollupHealthLogMetricsMonths", skip_serializing_if = "Option::is_none")]
    pub rollup_health_log_metrics_months: Option<i32>,
    #[serde(rename = "sessionExpirationDefault", skip_serializing_if = "Option::is_none")]
    pub session_expiration_default: Option<models::TypesDuration>,
    #[serde(rename = "sessionExpirationRemember", skip_serializing_if = "Option::is_none")]
    pub session_expiration_remember: Option<models::TypesDuration>,
    #[serde(rename = "sseTimeout", skip_serializing_if = "Option::is_none")]
    pub sse_timeout: Option<models::TypesDuration>,
    #[serde(rename = "systemClientKey", skip_serializing_if = "Option::is_none")]
    pub system_client_key: Option<String>,
    #[serde(rename = "systemHealthKey", skip_serializing_if = "Option::is_none")]
    pub system_health_key: Option<String>,
    #[serde(rename = "systemMetricsKey", skip_serializing_if = "Option::is_none")]
    pub system_metrics_key: Option<String>,
    #[serde(rename = "systemPprofKey", skip_serializing_if = "Option::is_none")]
    pub system_pprof_key: Option<String>,
    #[serde(rename = "trialDays", skip_serializing_if = "Option::is_none")]
    pub trial_days: Option<i32>,
    #[serde(rename = "uiDir", skip_serializing_if = "Option::is_none")]
    pub ui_dir: Option<String>,
    #[serde(rename = "uiHost", skip_serializing_if = "Option::is_none")]
    pub ui_host: Option<String>,
    #[serde(rename = "wellKnownResponses", skip_serializing_if = "Option::is_none")]
    pub well_known_responses: Option<std::collections::HashMap<String, models::ConfigWellKnownResponse>>,
}

impl ConfigApp {
    pub fn new() -> ConfigApp {
        ConfigApp {
            admin_email_addresses: None,
            admin_trusted_cidrs: None,
            base_url: None,
            cache_control: None,
            cloud_dev_key: None,
            cloud_endpoint: None,
            cloud_jwt: None,
            cloud_private_key: None,
            contact_feedback: None,
            contact_support: None,
            counter_time_zone: None,
            demo: None,
            disable_notifications: None,
            disable_signup: None,
            disable_tasks: None,
            disable_web_config: None,
            enable_custom_api: None,
            enable_demo: None,
            ignore_payment_failures: None,
            keep_calendar_event_days: None,
            keep_cook_meal_plan_days: None,
            keep_deleted_days: None,
            keep_expired_auth_household_days: None,
            keep_health_log_item_days: None,
            keep_health_log_metric_months: None,
            keep_inactive_auth_account_days: None,
            keep_notes_page_versions: None,
            keep_plan_task_days: None,
            motd: None,
            private_keys: None,
            proxy_address: None,
            proxy_header_email: None,
            proxy_header_name: None,
            rollup_budget_month_categories_months: None,
            rollup_budget_transactions_balance_months: None,
            rollup_budget_transactions_summary_months: None,
            rollup_health_log_metrics_days: None,
            rollup_health_log_metrics_months: None,
            session_expiration_default: None,
            session_expiration_remember: None,
            sse_timeout: None,
            system_client_key: None,
            system_health_key: None,
            system_metrics_key: None,
            system_pprof_key: None,
            trial_days: None,
            ui_dir: None,
            ui_host: None,
            well_known_responses: None,
        }
    }
}

