/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CryptolibKdf {
    #[serde(rename = "ecdhp256")]
    KDFECDHP256,
    #[serde(rename = "ecdhp256hkdfsha256")]
    KDFECDHP256HKDFSHA256,
    #[serde(rename = "argon2id")]
    BestKDF,
    #[serde(rename = "ecdhx25519mlkem768hkdfsha256")]
    KDFECDHX25519MLKEM768HKDFSHA256,
    #[serde(rename = "argon2id")]
    KDFArgon2ID,
    #[serde(rename = "ecdhx25519")]
    KDFECDHX25519,
    #[serde(rename = "ecdhx25519hkdfsha256")]
    KDFECDHX25519HKDFSHA256,
    #[serde(rename = "ecdhp384")]
    KDFECDHP384,
    #[serde(rename = "ecdhp384hkdfsha256")]
    KDFECDHP384HKDFSHA256,

}

impl std::fmt::Display for CryptolibKdf {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::KDFECDHP256 => write!(f, "ecdhp256"),
            Self::KDFECDHP256HKDFSHA256 => write!(f, "ecdhp256hkdfsha256"),
            Self::BestKDF => write!(f, "argon2id"),
            Self::KDFECDHX25519MLKEM768HKDFSHA256 => write!(f, "ecdhx25519mlkem768hkdfsha256"),
            Self::KDFArgon2ID => write!(f, "argon2id"),
            Self::KDFECDHX25519 => write!(f, "ecdhx25519"),
            Self::KDFECDHX25519HKDFSHA256 => write!(f, "ecdhx25519hkdfsha256"),
            Self::KDFECDHP384 => write!(f, "ecdhp384"),
            Self::KDFECDHP384HKDFSHA256 => write!(f, "ecdhp384hkdfsha256"),
        }
    }
}

impl Default for CryptolibKdf {
    fn default() -> CryptolibKdf {
        Self::KDFECDHP256
    }
}

