/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttplibServer {
    #[serde(rename = "listenAddress", skip_serializing_if = "Option::is_none")]
    pub listen_address: Option<String>,
    #[serde(rename = "rateLimitKey", skip_serializing_if = "Option::is_none")]
    pub rate_limit_key: Option<String>,
    #[serde(rename = "rateLimitPatterns", skip_serializing_if = "Option::is_none")]
    pub rate_limit_patterns: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "timeoutRead", skip_serializing_if = "Option::is_none")]
    pub timeout_read: Option<models::TypesDuration>,
    #[serde(rename = "timeoutReadHeader", skip_serializing_if = "Option::is_none")]
    pub timeout_read_header: Option<models::TypesDuration>,
    #[serde(rename = "timeoutWrite", skip_serializing_if = "Option::is_none")]
    pub timeout_write: Option<models::TypesDuration>,
    #[serde(rename = "tlsCertificateBase64", skip_serializing_if = "Option::is_none")]
    pub tls_certificate_base64: Option<String>,
    #[serde(rename = "tlsCertificatePath", skip_serializing_if = "Option::is_none")]
    pub tls_certificate_path: Option<String>,
    #[serde(rename = "tlsClientAuthCABase64", skip_serializing_if = "Option::is_none")]
    pub tls_client_auth_ca_base64: Option<String>,
    #[serde(rename = "tlsClientAuthCAPath", skip_serializing_if = "Option::is_none")]
    pub tls_client_auth_ca_path: Option<String>,
    #[serde(rename = "tlsKeyBase64", skip_serializing_if = "Option::is_none")]
    pub tls_key_base64: Option<String>,
    #[serde(rename = "tlsKeyPath", skip_serializing_if = "Option::is_none")]
    pub tls_key_path: Option<String>,
    #[serde(rename = "xForwardedTrustedCIDRs", skip_serializing_if = "Option::is_none")]
    pub x_forwarded_trusted_cidrs: Option<Vec<String>>,
}

impl HttplibServer {
    pub fn new() -> HttplibServer {
        HttplibServer {
            listen_address: None,
            rate_limit_key: None,
            rate_limit_patterns: None,
            timeout_read: None,
            timeout_read_header: None,
            timeout_write: None,
            tls_certificate_base64: None,
            tls_certificate_path: None,
            tls_client_auth_ca_base64: None,
            tls_client_auth_ca_path: None,
            tls_key_base64: None,
            tls_key_path: None,
            x_forwarded_trusted_cidrs: None,
        }
    }
}

