/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttplibClient {
    #[serde(rename = "noSystemCAs", skip_serializing_if = "Option::is_none")]
    pub no_system_cas: Option<bool>,
    #[serde(rename = "timeoutDial", skip_serializing_if = "Option::is_none")]
    pub timeout_dial: Option<models::TypesDuration>,
    #[serde(rename = "timeoutTLSHandshake", skip_serializing_if = "Option::is_none")]
    pub timeout_tls_handshake: Option<models::TypesDuration>,
    #[serde(rename = "tlsCABase64", skip_serializing_if = "Option::is_none")]
    pub tls_ca_base64: Option<String>,
    #[serde(rename = "tlsCAPath", skip_serializing_if = "Option::is_none")]
    pub tls_ca_path: Option<String>,
    #[serde(rename = "tlsCertificatesBase64", skip_serializing_if = "Option::is_none")]
    pub tls_certificates_base64: Option<Vec<String>>,
    #[serde(rename = "tlsCertificatesPath", skip_serializing_if = "Option::is_none")]
    pub tls_certificates_path: Option<Vec<String>>,
    #[serde(rename = "tlsKeysBase64", skip_serializing_if = "Option::is_none")]
    pub tls_keys_base64: Option<Vec<String>>,
    #[serde(rename = "tlsKeysPath", skip_serializing_if = "Option::is_none")]
    pub tls_keys_path: Option<Vec<String>>,
    #[serde(rename = "tlsSkipVerify", skip_serializing_if = "Option::is_none")]
    pub tls_skip_verify: Option<bool>,
}

impl HttplibClient {
    pub fn new() -> HttplibClient {
        HttplibClient {
            no_system_cas: None,
            timeout_dial: None,
            timeout_tls_handshake: None,
            tls_ca_base64: None,
            tls_ca_path: None,
            tls_certificates_base64: None,
            tls_certificates_path: None,
            tls_keys_base64: None,
            tls_keys_path: None,
            tls_skip_verify: None,
        }
    }
}

