/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwtRegisteredClaims {
    /// The \"aud\" (audience) claim identifies the recipients that the JWT is   intended for.  Each principal intended to process the JWT MUST   identify itself with a value in the audience claim.  If the principal   processing the claim does not identify itself with a value in the   \"aud\" claim when this claim is present, then the JWT MUST be   rejected.  In the general case, the \"aud\" value is an array of case-   sensitive strings, each containing a StringOrURI value.  In the   special case when the JWT has one audience, the \"aud\" value MAY be a   single case-sensitive string containing a StringOrURI value.  The   interpretation of audience values is generally application specific.   Use of this claim is OPTIONAL.
    #[serde(rename = "aud", skip_serializing_if = "Option::is_none")]
    pub aud: Option<Vec<String>>,
    /// The \"exp\" (expiration time) claim identifies the expiration time on   or after which the JWT MUST NOT be accepted for processing.  The   processing of the \"exp\" claim requires that the current date/time   MUST be before the expiration date/time listed in the \"exp\" claim.   Implementers MAY provide for some small leeway, usually no more than   a few minutes, to account for clock skew.  Its value MUST be a number   containing a NumericDate value.  Use of this claim is OPTIONAL.
    #[serde(rename = "exp", skip_serializing_if = "Option::is_none")]
    pub exp: Option<i32>,
    /// The \"iat\" (issued at) claim identifies the time at which the JWT was   issued.  This claim can be used to determine the age of the JWT.  Its   value MUST be a number containing a NumericDate value.  Use of this   claim is OPTIONAL.
    #[serde(rename = "iat", skip_serializing_if = "Option::is_none")]
    pub iat: Option<i32>,
    /// The \"iss\" (issuer) claim identifies the principal that issued the   JWT.  The processing of this claim is generally application specific.   The \"iss\" value is a case-sensitive string containing a StringOrURI   value.  Use of this claim is OPTIONAL.
    #[serde(rename = "iss", skip_serializing_if = "Option::is_none")]
    pub iss: Option<String>,
    /// The \"jti\" (JWT ID) claim provides a unique identifier for the JWT.   The identifier value MUST be assigned in a manner that ensures that   there is a negligible probability that the same value will be   accidentally assigned to a different data object; if the application   uses multiple issuers, collisions MUST be prevented among values   produced by different issuers as well.  The \"jti\" claim can be used   to prevent the JWT from being replayed.  The \"jti\" value is a case-   sensitive string.  Use of this claim is OPTIONAL.
    #[serde(rename = "jti", skip_serializing_if = "Option::is_none")]
    pub jti: Option<String>,
    /// The \"nbf\" (not before) claim identifies the time before which the JWT   MUST NOT be accepted for processing.  The processing of the \"nbf\"   claim requires that the current date/time MUST be after or equal to   the not-before date/time listed in the \"nbf\" claim.  Implementers MAY   provide for some small leeway, usually no more than a few minutes, to   account for clock skew.  Its value MUST be a number containing a   NumericDate value.  Use of this claim is OPTIONAL.
    #[serde(rename = "nbf", skip_serializing_if = "Option::is_none")]
    pub nbf: Option<i32>,
    /// The \"sub\" (subject) claim identifies the principal that is the   subject of the JWT.  The claims in a JWT are normally statements   about the subject.  The subject value MUST either be scoped to be   locally unique in the context of the issuer or be globally unique.   The processing of this claim is generally application specific.  The   \"sub\" value is a case-sensitive string containing a StringOrURI   value.  Use of this claim is OPTIONAL.
    #[serde(rename = "sub", skip_serializing_if = "Option::is_none")]
    pub sub: Option<String>,
}

impl JwtRegisteredClaims {
    pub fn new() -> JwtRegisteredClaims {
        JwtRegisteredClaims {
            aud: None,
            exp: None,
            iat: None,
            iss: None,
            jti: None,
            nbf: None,
            sub: None,
        }
    }
}

