/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsBudgetPayee {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<String>,
    #[serde(rename = "budgetCategoryID", skip_serializing_if = "Option::is_none")]
    pub budget_category_id: Option<uuid::Uuid>,
    #[serde(rename = "budgetTransactionAmount", skip_serializing_if = "Option::is_none")]
    pub budget_transaction_amount: Option<i32>,
    #[serde(rename = "cookMealPlanCount", skip_serializing_if = "Option::is_none")]
    pub cook_meal_plan_count: Option<i32>,
    #[serde(rename = "cookMealPlanLast", skip_serializing_if = "Option::is_none")]
    pub cook_meal_plan_last: Option<String>,
    #[serde(rename = "cookRestaurant", skip_serializing_if = "Option::is_none")]
    pub cook_restaurant: Option<bool>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "labelsValuesIDs", skip_serializing_if = "Option::is_none")]
    pub labels_values_ids: Option<Vec<String>>,
    #[serde(rename = "mealsDisliked", skip_serializing_if = "Option::is_none")]
    pub meals_disliked: Option<Vec<String>>,
    #[serde(rename = "mealsLiked", skip_serializing_if = "Option::is_none")]
    pub meals_liked: Option<Vec<String>>,
    #[serde(rename = "menuLink", skip_serializing_if = "Option::is_none")]
    pub menu_link: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<i32>,
    #[serde(rename = "shopStore", skip_serializing_if = "Option::is_none")]
    pub shop_store: Option<bool>,
    #[serde(rename = "shortID", skip_serializing_if = "Option::is_none")]
    pub short_id: Option<String>,
    #[serde(rename = "travelTime", skip_serializing_if = "Option::is_none")]
    pub travel_time: Option<i32>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ModelsBudgetPayee {
    pub fn new() -> ModelsBudgetPayee {
        ModelsBudgetPayee {
            address: None,
            auth_household_id: None,
            budget_category_id: None,
            budget_transaction_amount: None,
            cook_meal_plan_count: None,
            cook_meal_plan_last: None,
            cook_restaurant: None,
            created: None,
            icon: None,
            id: None,
            labels_values_ids: None,
            meals_disliked: None,
            meals_liked: None,
            menu_link: None,
            name: None,
            phone_number: None,
            price: None,
            rating: None,
            shop_store: None,
            short_id: None,
            travel_time: None,
            updated: None,
        }
    }
}

