/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthAccountPreferencesNotificationsHousehold {
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<String>,
    #[serde(rename = "ignoreDeviceBookmarkCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_bookmark_create: Option<bool>,
    #[serde(rename = "ignoreDeviceBudgetCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_budget_create: Option<bool>,
    #[serde(rename = "ignoreDeviceCalendarCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_calendar_create: Option<bool>,
    #[serde(rename = "ignoreDeviceCalendarEvent", skip_serializing_if = "Option::is_none")]
    pub ignore_device_calendar_event: Option<bool>,
    #[serde(rename = "ignoreDeviceCookCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_cook_create: Option<bool>,
    #[serde(rename = "ignoreDeviceCookMealPlanCook", skip_serializing_if = "Option::is_none")]
    pub ignore_device_cook_meal_plan_cook: Option<bool>,
    #[serde(rename = "ignoreDeviceCookMealPlanLeave", skip_serializing_if = "Option::is_none")]
    pub ignore_device_cook_meal_plan_leave: Option<bool>,
    #[serde(rename = "ignoreDeviceCookMealPlanPrep", skip_serializing_if = "Option::is_none")]
    pub ignore_device_cook_meal_plan_prep: Option<bool>,
    #[serde(rename = "ignoreDeviceInventoryCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_inventory_create: Option<bool>,
    #[serde(rename = "ignoreDeviceNotesCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_notes_create: Option<bool>,
    #[serde(rename = "ignoreDevicePlanCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_plan_create: Option<bool>,
    #[serde(rename = "ignoreDevicePlanTask", skip_serializing_if = "Option::is_none")]
    pub ignore_device_plan_task: Option<bool>,
    #[serde(rename = "ignoreDevicePlanTaskComplete", skip_serializing_if = "Option::is_none")]
    pub ignore_device_plan_task_complete: Option<bool>,
    #[serde(rename = "ignoreDeviceRewardCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_reward_create: Option<bool>,
    #[serde(rename = "ignoreDeviceSecretsCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_secrets_create: Option<bool>,
    #[serde(rename = "ignoreDeviceShopCreate", skip_serializing_if = "Option::is_none")]
    pub ignore_device_shop_create: Option<bool>,
    #[serde(rename = "ignoreEmailCalendarEvent", skip_serializing_if = "Option::is_none")]
    pub ignore_email_calendar_event: Option<bool>,
    #[serde(rename = "ignoreEmailCookMealPlanCook", skip_serializing_if = "Option::is_none")]
    pub ignore_email_cook_meal_plan_cook: Option<bool>,
    #[serde(rename = "ignoreEmailCookMealPlanLeave", skip_serializing_if = "Option::is_none")]
    pub ignore_email_cook_meal_plan_leave: Option<bool>,
    #[serde(rename = "ignoreEmailCookMealPlanPrep", skip_serializing_if = "Option::is_none")]
    pub ignore_email_cook_meal_plan_prep: Option<bool>,
    #[serde(rename = "ignoreEmailPlanTask", skip_serializing_if = "Option::is_none")]
    pub ignore_email_plan_task: Option<bool>,
}

impl ModelsAuthAccountPreferencesNotificationsHousehold {
    pub fn new() -> ModelsAuthAccountPreferencesNotificationsHousehold {
        ModelsAuthAccountPreferencesNotificationsHousehold {
            auth_household_id: None,
            ignore_device_bookmark_create: None,
            ignore_device_budget_create: None,
            ignore_device_calendar_create: None,
            ignore_device_calendar_event: None,
            ignore_device_cook_create: None,
            ignore_device_cook_meal_plan_cook: None,
            ignore_device_cook_meal_plan_leave: None,
            ignore_device_cook_meal_plan_prep: None,
            ignore_device_inventory_create: None,
            ignore_device_notes_create: None,
            ignore_device_plan_create: None,
            ignore_device_plan_task: None,
            ignore_device_plan_task_complete: None,
            ignore_device_reward_create: None,
            ignore_device_secrets_create: None,
            ignore_device_shop_create: None,
            ignore_email_calendar_event: None,
            ignore_email_cook_meal_plan_cook: None,
            ignore_email_cook_meal_plan_leave: None,
            ignore_email_cook_meal_plan_prep: None,
            ignore_email_plan_task: None,
        }
    }
}

