/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsBudgetMonth {
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<uuid::Uuid>,
    #[serde(rename = "budgetMonthCategories", skip_serializing_if = "Option::is_none")]
    pub budget_month_categories: Option<Vec<models::ModelsBudgetMonthCategory>>,
    #[serde(rename = "budgetMonthCategoryAmount", skip_serializing_if = "Option::is_none")]
    pub budget_month_category_amount: Option<i32>,
    #[serde(rename = "budgetTransactionAmountIncome", skip_serializing_if = "Option::is_none")]
    pub budget_transaction_amount_income: Option<i32>,
    #[serde(rename = "budgetTransactionAmountIncomeRemaining", skip_serializing_if = "Option::is_none")]
    pub budget_transaction_amount_income_remaining: Option<i32>,
    #[serde(rename = "yearMonth", skip_serializing_if = "Option::is_none")]
    pub year_month: Option<i32>,
}

impl ModelsBudgetMonth {
    pub fn new() -> ModelsBudgetMonth {
        ModelsBudgetMonth {
            auth_household_id: None,
            budget_month_categories: None,
            budget_month_category_amount: None,
            budget_transaction_amount_income: None,
            budget_transaction_amount_income_remaining: None,
            year_month: None,
        }
    }
}

