/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthHousehold {
    #[serde(rename = "backupEncryptionKey", skip_serializing_if = "Option::is_none")]
    pub backup_encryption_key: Option<String>,
    #[serde(rename = "countMembers", skip_serializing_if = "Option::is_none")]
    pub count_members: Option<i32>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "demo", skip_serializing_if = "Option::is_none")]
    pub demo: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::ModelsAuthHouseholdMember>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "preferences", skip_serializing_if = "Option::is_none")]
    pub preferences: Option<Box<models::ModelsAuthHouseholdPreferences>>,
    #[serde(rename = "selfHostedID", skip_serializing_if = "Option::is_none")]
    pub self_hosted_id: Option<String>,
    #[serde(rename = "subscriptionCustomerID", skip_serializing_if = "Option::is_none")]
    pub subscription_customer_id: Option<String>,
    #[serde(rename = "subscriptionExpires", skip_serializing_if = "Option::is_none")]
    pub subscription_expires: Option<String>,
    #[serde(rename = "subscriptionID", skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<String>,
    #[serde(rename = "subscriptionLastTransactionID", skip_serializing_if = "Option::is_none")]
    pub subscription_last_transaction_id: Option<String>,
    #[serde(rename = "subscriptionProcessor", skip_serializing_if = "Option::is_none")]
    pub subscription_processor: Option<models::ModelsAuthHouseholdSubscriptionProcessor>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ModelsAuthHousehold {
    pub fn new() -> ModelsAuthHousehold {
        ModelsAuthHousehold {
            backup_encryption_key: None,
            count_members: None,
            created: None,
            demo: None,
            id: None,
            members: None,
            name: None,
            preferences: None,
            self_hosted_id: None,
            subscription_customer_id: None,
            subscription_expires: None,
            subscription_id: None,
            subscription_last_transaction_id: None,
            subscription_processor: None,
            updated: None,
        }
    }
}

