/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthAccount {
    /// AuthOIDCClientIDs and the scopes the AuthAccountID has granted access to.
    #[serde(rename = "authOIDCClientIDs", skip_serializing_if = "Option::is_none")]
    pub auth_oidc_client_ids: Option<std::collections::HashMap<String, Vec<String>>>,
    /// A list of IDs to collapse.
    #[serde(rename = "collapsedNotesPages", skip_serializing_if = "Option::is_none")]
    pub collapsed_notes_pages: Option<Vec<String>>,
    /// A list of IDs to collapse.
    #[serde(rename = "collapsedPlanProjects", skip_serializing_if = "Option::is_none")]
    pub collapsed_plan_projects: Option<Vec<String>>,
    /// A list of IDs to collapse.
    #[serde(rename = "collapsedPlanTasks", skip_serializing_if = "Option::is_none")]
    pub collapsed_plan_tasks: Option<Vec<String>>,
    /// Timestamp account was created.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// The next timestamp for the agenda.
    #[serde(rename = "dailyAgendaNext", skip_serializing_if = "Option::is_none")]
    pub daily_agenda_next: Option<String>,
    /// When to send the daily agenda.
    #[serde(rename = "dailyAgendaTime", skip_serializing_if = "Option::is_none")]
    pub daily_agenda_time: Option<String>,
    /// List of Delegations
    #[serde(rename = "delegations", skip_serializing_if = "Option::is_none")]
    pub delegations: Option<Vec<models::ModelsAuthAccountDelegation>>,
    /// Primary email address of user.
    #[serde(rename = "emailAddress", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    /// EmailAuthDisabled disables EmailAuth.
    #[serde(rename = "emailAuthDisabled", skip_serializing_if = "Option::is_none")]
    pub email_auth_disabled: Option<bool>,
    /// EmailAuthTokenJSON is used for EmailAuth during signin.
    #[serde(rename = "emailAuthToken", skip_serializing_if = "Option::is_none")]
    pub email_auth_token: Option<uuid::Uuid>,
    /// Number of hours to associate health item outputs to inputs.
    #[serde(rename = "healthItemCorrelationHours", skip_serializing_if = "Option::is_none")]
    pub health_item_correlation_hours: Option<i32>,
    /// A list of iCalendar IDs to hide.
    #[serde(rename = "hideCalendarICalendars", skip_serializing_if = "Option::is_none")]
    pub hide_calendar_i_calendars: Option<Vec<String>>,
    /// ICalendarID for the account.
    #[serde(rename = "icalendarID", skip_serializing_if = "Option::is_none")]
    pub icalendar_id: Option<uuid::Uuid>,
    /// ID of the account.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// ISO639Code is the code used for translations.
    #[serde(rename = "iso639Code", skip_serializing_if = "Option::is_none")]
    pub iso639_code: Option<String>,
    /// Timestamp of the last time the account signed in.
    #[serde(rename = "lastActivity", skip_serializing_if = "Option::is_none")]
    pub last_activity: Option<String>,
    /// Name of the AuthAccount user.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Code from OIDC provider to check during sign in/up.
    #[serde(rename = "oidcCode", skip_serializing_if = "Option::is_none")]
    pub oidc_code: Option<String>,
    /// Issuer name used for OIDC.
    #[serde(rename = "oidcIssuer", skip_serializing_if = "Option::is_none")]
    pub oidc_issuer: Option<String>,
    /// State used to generate OIDC keys.
    #[serde(rename = "oidcState", skip_serializing_if = "Option::is_none")]
    pub oidc_state: Option<String>,
    /// Password to use for sign in/up.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Whether the account is enabled for password authentication.
    #[serde(rename = "passwordEnabled", skip_serializing_if = "Option::is_none")]
    pub password_enabled: Option<bool>,
    /// Permissions for the account when creating a new session.
    #[serde(rename = "permissionsAccount", skip_serializing_if = "Option::is_none")]
    pub permissions_account: Option<Box<models::ModelsPermissions>>,
    /// Permissions for the households when creating a new session.
    #[serde(rename = "permissionsHouseholds", skip_serializing_if = "Option::is_none")]
    pub permissions_households: Option<std::collections::HashMap<String, models::ModelsPermissions>>,
    /// Preferences for the account.
    #[serde(rename = "preferences", skip_serializing_if = "Option::is_none")]
    pub preferences: Option<Box<models::ModelsAuthAccountPreferences>>,
    /// The primary AuthHouseholdID, used by short links.
    #[serde(rename = "primaryAuthHouseholdID", skip_serializing_if = "Option::is_none")]
    pub primary_auth_household_id: Option<uuid::Uuid>,
    /// PrivateKeys for decrypting secrets.
    #[serde(rename = "privateKeys", skip_serializing_if = "Option::is_none")]
    pub private_keys: Option<Vec<models::ModelsAuthAccountPrivateKey>>,
    /// PublicKey for encrypting secrets.
    #[serde(rename = "publicKey", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Box<models::CryptolibKeyCryptolibKeyProviderPublic>>,
    /// Sets a longer timeout for the AuthSession.
    #[serde(rename = "rememberMe", skip_serializing_if = "Option::is_none")]
    pub remember_me: Option<bool>,
    /// SelfHosted ID of the account, used when creating CloudHouseholds.
    #[serde(rename = "selfHostedID", skip_serializing_if = "Option::is_none")]
    pub self_hosted_id: Option<uuid::Uuid>,
    /// Whether the account has gone through setup.
    #[serde(rename = "setup", skip_serializing_if = "Option::is_none")]
    pub setup: Option<bool>,
    /// Used by notifications and UI to determine local times.
    #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    /// ToS must be accepted to use the app.
    #[serde(rename = "tosAccepted", skip_serializing_if = "Option::is_none")]
    pub tos_accepted: Option<bool>,
    /// Backup code to recover TOTP for JSON.
    #[serde(rename = "totpBackup", skip_serializing_if = "Option::is_none")]
    pub totp_backup: Option<String>,
    /// Code from the TOTP generator.
    #[serde(rename = "totpCode", skip_serializing_if = "Option::is_none")]
    pub totp_code: Option<String>,
    /// Will check for TOTP code during sign in.
    #[serde(rename = "totpEnabled", skip_serializing_if = "Option::is_none")]
    pub totp_enabled: Option<bool>,
    /// QR Code version of the TOTPSecret.
    #[serde(rename = "totpQR", skip_serializing_if = "Option::is_none")]
    pub totp_qr: Option<String>,
    /// Secret to setup a TOTP generator for JSON.
    #[serde(rename = "totpSecret", skip_serializing_if = "Option::is_none")]
    pub totp_secret: Option<String>,
    /// Timestamp for when account was last updated.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    /// Sets the UserAgent for the initial session after account creation.
    #[serde(rename = "userAgent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<models::TypesUserAgent>,
    /// Accounts must be verified to receive email notifications.
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    /// WebAuthnCreation is used during signup and webauthnenrollment.
    #[serde(rename = "webAuthnCreation", skip_serializing_if = "Option::is_none")]
    pub web_authn_creation: Option<Box<models::WebauthnCredentialCreation>>,
    /// WebAuthnCredentials is a list of usable WebAuthn credentials for authenticating an AuthAccount.
    #[serde(rename = "webAuthnCredentials", skip_serializing_if = "Option::is_none")]
    pub web_authn_credentials: Option<Vec<models::WebauthnCredential>>,
    /// WebAuthnRequest is used during signin.
    #[serde(rename = "webAuthnRequest", skip_serializing_if = "Option::is_none")]
    pub web_authn_request: Option<Box<models::WebauthnCredentialRequest>>,
}

impl ModelsAuthAccount {
    pub fn new() -> ModelsAuthAccount {
        ModelsAuthAccount {
            auth_oidc_client_ids: None,
            collapsed_notes_pages: None,
            collapsed_plan_projects: None,
            collapsed_plan_tasks: None,
            created: None,
            daily_agenda_next: None,
            daily_agenda_time: None,
            delegations: None,
            email_address: None,
            email_auth_disabled: None,
            email_auth_token: None,
            health_item_correlation_hours: None,
            hide_calendar_i_calendars: None,
            icalendar_id: None,
            id: None,
            iso639_code: None,
            last_activity: None,
            name: None,
            oidc_code: None,
            oidc_issuer: None,
            oidc_state: None,
            password: None,
            password_enabled: None,
            permissions_account: None,
            permissions_households: None,
            preferences: None,
            primary_auth_household_id: None,
            private_keys: None,
            public_key: None,
            remember_me: None,
            self_hosted_id: None,
            setup: None,
            time_zone: None,
            tos_accepted: None,
            totp_backup: None,
            totp_code: None,
            totp_enabled: None,
            totp_qr: None,
            totp_secret: None,
            updated: None,
            user_agent: None,
            verified: None,
            web_authn_creation: None,
            web_authn_credentials: None,
            web_authn_request: None,
        }
    }
}

