/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthHouseholdPreferences {
    #[serde(rename = "colorBudgetRecurrenceEvents", skip_serializing_if = "Option::is_none")]
    pub color_budget_recurrence_events: Option<models::TypesColor>,
    #[serde(rename = "colorCalendarEvents", skip_serializing_if = "Option::is_none")]
    pub color_calendar_events: Option<models::TypesColor>,
    #[serde(rename = "colorCookMealPlanEvents", skip_serializing_if = "Option::is_none")]
    pub color_cook_meal_plan_events: Option<models::TypesColor>,
    #[serde(rename = "colorPlanTaskEvents", skip_serializing_if = "Option::is_none")]
    pub color_plan_task_events: Option<models::TypesColor>,
    #[serde(rename = "colors", skip_serializing_if = "Option::is_none")]
    pub colors: Option<Vec<models::ModelsColor>>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::TypesCurrency>,
    #[serde(rename = "disableCloudAPN", skip_serializing_if = "Option::is_none")]
    pub disable_cloud_apn: Option<bool>,
    #[serde(rename = "hideComponents", skip_serializing_if = "Option::is_none")]
    pub hide_components: Option<Vec<String>>,
}

impl ModelsAuthHouseholdPreferences {
    pub fn new() -> ModelsAuthHouseholdPreferences {
        ModelsAuthHouseholdPreferences {
            color_budget_recurrence_events: None,
            color_calendar_events: None,
            color_cook_meal_plan_events: None,
            color_plan_task_events: None,
            colors: None,
            currency: None,
            disable_cloud_apn: None,
            hide_components: None,
        }
    }
}

