/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsShopItem {
    #[serde(rename = "authAccountID", skip_serializing_if = "Option::is_none")]
    pub auth_account_id: Option<String>,
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<String>,
    #[serde(rename = "budgetPayeeID", skip_serializing_if = "Option::is_none")]
    pub budget_payee_id: Option<uuid::Uuid>,
    #[serde(rename = "cookMealPlanID", skip_serializing_if = "Option::is_none")]
    pub cook_meal_plan_id: Option<String>,
    #[serde(rename = "cookRecipeID", skip_serializing_if = "Option::is_none")]
    pub cook_recipe_id: Option<uuid::Uuid>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "inCart", skip_serializing_if = "Option::is_none")]
    pub in_cart: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nextDate", skip_serializing_if = "Option::is_none")]
    pub next_date: Option<String>,
    #[serde(rename = "planProjectID", skip_serializing_if = "Option::is_none")]
    pub plan_project_id: Option<String>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    #[serde(rename = "recurrence", skip_serializing_if = "Option::is_none")]
    pub recurrence: Option<Box<models::TypesRecurrence>>,
    #[serde(rename = "shopCategoryID", skip_serializing_if = "Option::is_none")]
    pub shop_category_id: Option<uuid::Uuid>,
    #[serde(rename = "shopListID", skip_serializing_if = "Option::is_none")]
    pub shop_list_id: Option<uuid::Uuid>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ModelsShopItem {
    pub fn new() -> ModelsShopItem {
        ModelsShopItem {
            auth_account_id: None,
            auth_household_id: None,
            budget_payee_id: None,
            cook_meal_plan_id: None,
            cook_recipe_id: None,
            created: None,
            id: None,
            in_cart: None,
            name: None,
            next_date: None,
            plan_project_id: None,
            position: None,
            price: None,
            recurrence: None,
            shop_category_id: None,
            shop_list_id: None,
            updated: None,
        }
    }
}

