/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsPermissions {
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<models::ModelsPermission>,
    #[serde(rename = "bookmarks", skip_serializing_if = "Option::is_none")]
    pub bookmarks: Option<models::ModelsPermission>,
    #[serde(rename = "budget", skip_serializing_if = "Option::is_none")]
    pub budget: Option<models::ModelsPermission>,
    #[serde(rename = "calendar", skip_serializing_if = "Option::is_none")]
    pub calendar: Option<models::ModelsPermission>,
    #[serde(rename = "cook", skip_serializing_if = "Option::is_none")]
    pub cook: Option<models::ModelsPermission>,
    #[serde(rename = "health", skip_serializing_if = "Option::is_none")]
    pub health: Option<models::ModelsPermission>,
    #[serde(rename = "inventory", skip_serializing_if = "Option::is_none")]
    pub inventory: Option<models::ModelsPermission>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<models::ModelsPermission>,
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<models::ModelsPermission>,
    #[serde(rename = "reward", skip_serializing_if = "Option::is_none")]
    pub reward: Option<models::ModelsPermission>,
    #[serde(rename = "secrets", skip_serializing_if = "Option::is_none")]
    pub secrets: Option<models::ModelsPermission>,
    #[serde(rename = "shop", skip_serializing_if = "Option::is_none")]
    pub shop: Option<models::ModelsPermission>,
}

impl ModelsPermissions {
    pub fn new() -> ModelsPermissions {
        ModelsPermissions {
            auth: None,
            bookmarks: None,
            budget: None,
            calendar: None,
            cook: None,
            health: None,
            inventory: None,
            notes: None,
            plan: None,
            reward: None,
            secrets: None,
            shop: None,
        }
    }
}

