/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModelsModelType {
    #[serde(rename = "auth_oidc_client")]
    ModelTypeAuthOIDCClient,
    #[serde(rename = "reward_card")]
    ModelTypeRewardCard,
    #[serde(rename = "shop_category")]
    ModelTypeShopCategory,
    #[serde(rename = "plan_task")]
    ModelTypePlanTask,
    #[serde(rename = "labels_value")]
    ModelTypeLabelsValue,
    #[serde(rename = "health_item")]
    ModelTypeHealthItem,
    #[serde(rename = "plan_project")]
    ModelTypePlanProject,
    #[serde(rename = "shop_item")]
    ModelTypeShopItem,
    #[serde(rename = "auth_household")]
    ModelTypeAuthHousehold,
    #[serde(rename = "inventory_collection")]
    ModelTypeInventoryCollection,
    #[serde(rename = "notification")]
    ModelTypeNotification,
    #[serde(rename = "change")]
    ModelTypeChange,
    #[serde(rename = "budget_month")]
    ModelTypeBudgetMonth,
    #[serde(rename = "notes_page")]
    ModelTypeNotesPage,
    #[serde(rename = "auth_account_delegation")]
    ModelTypeAuthAccountDelegation,
    #[serde(rename = "budget_account")]
    ModelTypeBudgetAccount,
    #[serde(rename = "budget_category")]
    ModelTypeBudgetCategory,
    #[serde(rename = "calendar_event")]
    ModelTypeCalendarEvent,
    #[serde(rename = "calendar_icalendar")]
    ModelTypeCalendarICalendar,
    #[serde(rename = "budget_transaction")]
    ModelTypeBudgetTransaction,
    #[serde(rename = "budget_payee")]
    ModelTypeBudgetPayee,
    #[serde(rename = "cloud_backup")]
    ModelTypeCloudBackup,
    #[serde(rename = "budget_transaction_account")]
    ModelTypeBudgetTransactionAccount,
    #[serde(rename = "shop_list")]
    ModelTypeShopList,
    #[serde(rename = "feature_candidate")]
    ModelTypeFeatureCandidate,
    #[serde(rename = "auth_oidc_code")]
    ModelTypeAuthOIDCCode,
    #[serde(rename = "auth_household_member")]
    ModelTypeAuthHouseholdMember,
    #[serde(rename = "cook_recipe")]
    ModelTypeCookRecipe,
    #[serde(rename = "cook_meal_plan")]
    ModelTypeCookMealPlan,
    #[serde(rename = "secrets_vault")]
    ModelTypeSecretsVault,
    #[serde(rename = "cook_meal_time")]
    ModelTypeCookMealTime,
    #[serde(rename = "budget_transaction_category")]
    ModelTypeBudgetTransactionCategory,
    #[serde(rename = "inventory_item")]
    ModelTypeInventoryItem,
    #[serde(rename = "auth_account")]
    ModelTypeAuthAccount,
    #[serde(rename = "auth_account_notify")]
    ModelTypeAuthAccountNotify,
    #[serde(rename = "config_key")]
    ModelTypeConfigKey,
    #[serde(rename = "bookmark")]
    ModelTypeBookmark,
    #[serde(rename = "budget_month_category")]
    ModelTypeBudgetMonthCategory,
    #[serde(rename = "budget_recurrence")]
    ModelTypeBudgetRecurrence,
    #[serde(rename = "health_log_item")]
    ModelTypeHealthLogItem,
    #[serde(rename = "feature_vote")]
    ModelTypeFeatureVote,
    #[serde(rename = "auth_session")]
    ModelTypeAuthSession,

}

impl std::fmt::Display for ModelsModelType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ModelTypeAuthOIDCClient => write!(f, "auth_oidc_client"),
            Self::ModelTypeRewardCard => write!(f, "reward_card"),
            Self::ModelTypeShopCategory => write!(f, "shop_category"),
            Self::ModelTypePlanTask => write!(f, "plan_task"),
            Self::ModelTypeLabelsValue => write!(f, "labels_value"),
            Self::ModelTypeHealthItem => write!(f, "health_item"),
            Self::ModelTypePlanProject => write!(f, "plan_project"),
            Self::ModelTypeShopItem => write!(f, "shop_item"),
            Self::ModelTypeAuthHousehold => write!(f, "auth_household"),
            Self::ModelTypeInventoryCollection => write!(f, "inventory_collection"),
            Self::ModelTypeNotification => write!(f, "notification"),
            Self::ModelTypeChange => write!(f, "change"),
            Self::ModelTypeBudgetMonth => write!(f, "budget_month"),
            Self::ModelTypeNotesPage => write!(f, "notes_page"),
            Self::ModelTypeAuthAccountDelegation => write!(f, "auth_account_delegation"),
            Self::ModelTypeBudgetAccount => write!(f, "budget_account"),
            Self::ModelTypeBudgetCategory => write!(f, "budget_category"),
            Self::ModelTypeCalendarEvent => write!(f, "calendar_event"),
            Self::ModelTypeCalendarICalendar => write!(f, "calendar_icalendar"),
            Self::ModelTypeBudgetTransaction => write!(f, "budget_transaction"),
            Self::ModelTypeBudgetPayee => write!(f, "budget_payee"),
            Self::ModelTypeCloudBackup => write!(f, "cloud_backup"),
            Self::ModelTypeBudgetTransactionAccount => write!(f, "budget_transaction_account"),
            Self::ModelTypeShopList => write!(f, "shop_list"),
            Self::ModelTypeFeatureCandidate => write!(f, "feature_candidate"),
            Self::ModelTypeAuthOIDCCode => write!(f, "auth_oidc_code"),
            Self::ModelTypeAuthHouseholdMember => write!(f, "auth_household_member"),
            Self::ModelTypeCookRecipe => write!(f, "cook_recipe"),
            Self::ModelTypeCookMealPlan => write!(f, "cook_meal_plan"),
            Self::ModelTypeSecretsVault => write!(f, "secrets_vault"),
            Self::ModelTypeCookMealTime => write!(f, "cook_meal_time"),
            Self::ModelTypeBudgetTransactionCategory => write!(f, "budget_transaction_category"),
            Self::ModelTypeInventoryItem => write!(f, "inventory_item"),
            Self::ModelTypeAuthAccount => write!(f, "auth_account"),
            Self::ModelTypeAuthAccountNotify => write!(f, "auth_account_notify"),
            Self::ModelTypeConfigKey => write!(f, "config_key"),
            Self::ModelTypeBookmark => write!(f, "bookmark"),
            Self::ModelTypeBudgetMonthCategory => write!(f, "budget_month_category"),
            Self::ModelTypeBudgetRecurrence => write!(f, "budget_recurrence"),
            Self::ModelTypeHealthLogItem => write!(f, "health_log_item"),
            Self::ModelTypeFeatureVote => write!(f, "feature_vote"),
            Self::ModelTypeAuthSession => write!(f, "auth_session"),
        }
    }
}

impl Default for ModelsModelType {
    fn default() -> ModelsModelType {
        Self::ModelTypeAuthOIDCClient
    }
}

