/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsCalendarEvent {
    #[serde(rename = "authAccountID", skip_serializing_if = "Option::is_none")]
    pub auth_account_id: Option<uuid::Uuid>,
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<uuid::Uuid>,
    #[serde(rename = "calendarICalendarID", skip_serializing_if = "Option::is_none")]
    pub calendar_i_calendar_id: Option<uuid::Uuid>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::TypesColor>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Deprecated: use Recurrence.End  TODO remove 2026-05-06
    #[serde(rename = "dateEnd", skip_serializing_if = "Option::is_none")]
    pub date_end: Option<String>,
    /// start of event or recurrence
    #[serde(rename = "dateStart", skip_serializing_if = "Option::is_none")]
    pub date_start: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    #[serde(rename = "iCalendarUID", skip_serializing_if = "Option::is_none")]
    pub i_calendar_uid: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Deprecated: Use Reminders  TODO remove 2026-05-06
    #[serde(rename = "notifyOffset", skip_serializing_if = "Option::is_none")]
    pub notify_offset: Option<i32>,
    #[serde(rename = "participants", skip_serializing_if = "Option::is_none")]
    pub participants: Option<Vec<String>>,
    #[serde(rename = "recurrence", skip_serializing_if = "Option::is_none")]
    pub recurrence: Option<Box<models::TypesRecurrence>>,
    #[serde(rename = "remindersEnd", skip_serializing_if = "Option::is_none")]
    pub reminders_end: Option<Vec<i32>>,
    #[serde(rename = "remindersStart", skip_serializing_if = "Option::is_none")]
    pub reminders_start: Option<Vec<i32>>,
    #[serde(rename = "skipDays", skip_serializing_if = "Option::is_none")]
    pub skip_days: Option<Vec<models::TypesCivilDate>>,
    #[serde(rename = "timeStart", skip_serializing_if = "Option::is_none")]
    pub time_start: Option<String>,
    #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    #[serde(rename = "timestampEnd", skip_serializing_if = "Option::is_none")]
    pub timestamp_end: Option<String>,
    #[serde(rename = "timestampStart", skip_serializing_if = "Option::is_none")]
    pub timestamp_start: Option<String>,
    #[serde(rename = "travelTime", skip_serializing_if = "Option::is_none")]
    pub travel_time: Option<i32>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ModelsCalendarEvent {
    pub fn new() -> ModelsCalendarEvent {
        ModelsCalendarEvent {
            auth_account_id: None,
            auth_household_id: None,
            calendar_i_calendar_id: None,
            color: None,
            created: None,
            date_end: None,
            date_start: None,
            details: None,
            duration: None,
            i_calendar_uid: None,
            id: None,
            location: None,
            name: None,
            notify_offset: None,
            participants: None,
            recurrence: None,
            reminders_end: None,
            reminders_start: None,
            skip_days: None,
            time_start: None,
            time_zone: None,
            timestamp_end: None,
            timestamp_start: None,
            travel_time: None,
            updated: None,
        }
    }
}

