/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsPlanTask {
    #[serde(rename = "assignees", skip_serializing_if = "Option::is_none")]
    pub assignees: Option<Vec<String>>,
    #[serde(rename = "authAccountID", skip_serializing_if = "Option::is_none")]
    pub auth_account_id: Option<uuid::Uuid>,
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<uuid::Uuid>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::TypesColor>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Deprecated: use Recurrence.End  TODO remove 2026-05-06
    #[serde(rename = "dateEnd", skip_serializing_if = "Option::is_none")]
    pub date_end: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "done", skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
    #[serde(rename = "dueDate", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "inventoryItemID", skip_serializing_if = "Option::is_none")]
    pub inventory_item_id: Option<uuid::Uuid>,
    #[serde(rename = "lastDoneBy", skip_serializing_if = "Option::is_none")]
    pub last_done_by: Option<String>,
    #[serde(rename = "lastDoneDate", skip_serializing_if = "Option::is_none")]
    pub last_done_date: Option<Box<models::TypesCivilDate>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<bool>,
    #[serde(rename = "parentID", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<uuid::Uuid>,
    #[serde(rename = "planProjectID", skip_serializing_if = "Option::is_none")]
    pub plan_project_id: Option<uuid::Uuid>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    #[serde(rename = "recurOnDone", skip_serializing_if = "Option::is_none")]
    pub recur_on_done: Option<bool>,
    #[serde(rename = "recurrence", skip_serializing_if = "Option::is_none")]
    pub recurrence: Option<Box<models::TypesRecurrence>>,
    #[serde(rename = "shortID", skip_serializing_if = "Option::is_none")]
    pub short_id: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<bool>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ModelsPlanTask {
    pub fn new() -> ModelsPlanTask {
        ModelsPlanTask {
            assignees: None,
            auth_account_id: None,
            auth_household_id: None,
            color: None,
            created: None,
            date_end: None,
            details: None,
            done: None,
            due_date: None,
            duration: None,
            id: None,
            inventory_item_id: None,
            last_done_by: None,
            last_done_date: None,
            name: None,
            notify: None,
            parent_id: None,
            plan_project_id: None,
            position: None,
            recur_on_done: None,
            recurrence: None,
            short_id: None,
            tags: None,
            template: None,
            updated: None,
        }
    }
}

