/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthAccountDelegation {
    #[serde(rename = "access", skip_serializing_if = "Option::is_none")]
    pub access: Option<Box<models::ModelsAuthAccountDelegationAccess>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "sourceID", skip_serializing_if = "Option::is_none")]
    pub source_id: Option<String>,
    #[serde(rename = "targetID", skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
}

impl ModelsAuthAccountDelegation {
    pub fn new() -> ModelsAuthAccountDelegation {
        ModelsAuthAccountDelegation {
            access: None,
            id: None,
            source_id: None,
            target_id: None,
        }
    }
}

