/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsCookMealPlan {
    #[serde(rename = "authAccountID", skip_serializing_if = "Option::is_none")]
    pub auth_account_id: Option<uuid::Uuid>,
    #[serde(rename = "authHouseholdID", skip_serializing_if = "Option::is_none")]
    pub auth_household_id: Option<uuid::Uuid>,
    #[serde(rename = "budgetPayeeID", skip_serializing_if = "Option::is_none")]
    pub budget_payee_id: Option<uuid::Uuid>,
    #[serde(rename = "cookMealTimeID", skip_serializing_if = "Option::is_none")]
    pub cook_meal_time_id: Option<uuid::Uuid>,
    #[serde(rename = "cookRecipeID", skip_serializing_if = "Option::is_none")]
    pub cook_recipe_id: Option<uuid::Uuid>,
    #[serde(rename = "cookRecipeScale", skip_serializing_if = "Option::is_none")]
    pub cook_recipe_scale: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "customRecipe", skip_serializing_if = "Option::is_none")]
    pub custom_recipe: Option<String>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "notificationTimeCook", skip_serializing_if = "Option::is_none")]
    pub notification_time_cook: Option<String>,
    #[serde(rename = "notificationTimeLeave", skip_serializing_if = "Option::is_none")]
    pub notification_time_leave: Option<String>,
    #[serde(rename = "notificationTimePrep", skip_serializing_if = "Option::is_none")]
    pub notification_time_prep: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl ModelsCookMealPlan {
    pub fn new() -> ModelsCookMealPlan {
        ModelsCookMealPlan {
            auth_account_id: None,
            auth_household_id: None,
            budget_payee_id: None,
            cook_meal_time_id: None,
            cook_recipe_id: None,
            cook_recipe_scale: None,
            created: None,
            custom_recipe: None,
            date: None,
            id: None,
            notification_time_cook: None,
            notification_time_leave: None,
            notification_time_prep: None,
            time: None,
            updated: None,
        }
    }
}

