/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthSession {
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    #[serde(rename = "authAccountID", skip_serializing_if = "Option::is_none")]
    pub auth_account_id: Option<uuid::Uuid>,
    #[serde(rename = "authHouseholdsPermissions", skip_serializing_if = "Option::is_none")]
    pub auth_households_permissions: Option<std::collections::HashMap<String, models::ModelsPermissions>>,
    #[serde(rename = "authHouseholdsPermissionsLabels", skip_serializing_if = "Option::is_none")]
    pub auth_households_permissions_labels: Option<std::collections::HashMap<String, std::collections::HashMap<String, models::ModelsPermission>>>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "delegations", skip_serializing_if = "Option::is_none")]
    pub delegations: Option<Vec<models::ModelsAuthAccountDelegation>>,
    #[serde(rename = "expires", skip_serializing_if = "Option::is_none")]
    pub expires: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "notifyAPN", skip_serializing_if = "Option::is_none")]
    pub notify_apn: Option<String>,
    #[serde(rename = "notifyWebPush", skip_serializing_if = "Option::is_none")]
    pub notify_web_push: Option<Box<models::NotifyWebPushClient>>,
    #[serde(rename = "permissionsAccount", skip_serializing_if = "Option::is_none")]
    pub permissions_account: Option<Box<models::ModelsPermissions>>,
    #[serde(rename = "permissionsHouseholds", skip_serializing_if = "Option::is_none")]
    pub permissions_households: Option<std::collections::HashMap<String, models::ModelsPermissions>>,
    #[serde(rename = "primaryAuthHouseholdID", skip_serializing_if = "Option::is_none")]
    pub primary_auth_household_id: Option<String>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<uuid::Uuid>,
    #[serde(rename = "userAgent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<models::TypesUserAgent>,
}

impl ModelsAuthSession {
    pub fn new() -> ModelsAuthSession {
        ModelsAuthSession {
            admin: None,
            auth_account_id: None,
            auth_households_permissions: None,
            auth_households_permissions_labels: None,
            created: None,
            delegations: None,
            expires: None,
            id: None,
            name: None,
            notify_apn: None,
            notify_web_push: None,
            permissions_account: None,
            permissions_households: None,
            primary_auth_household_id: None,
            token: None,
            user_agent: None,
        }
    }
}

