/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsAuthAccountPreferences {
    #[serde(rename = "colorAccent", skip_serializing_if = "Option::is_none")]
    pub color_accent: Option<models::TypesColor>,
    #[serde(rename = "colorNegative", skip_serializing_if = "Option::is_none")]
    pub color_negative: Option<models::TypesColor>,
    #[serde(rename = "colorPositive", skip_serializing_if = "Option::is_none")]
    pub color_positive: Option<models::TypesColor>,
    #[serde(rename = "colorPrimary", skip_serializing_if = "Option::is_none")]
    pub color_primary: Option<models::TypesColor>,
    #[serde(rename = "colorSecondary", skip_serializing_if = "Option::is_none")]
    pub color_secondary: Option<models::TypesColor>,
    #[serde(rename = "colors", skip_serializing_if = "Option::is_none")]
    pub colors: Option<Vec<models::ModelsColor>>,
    #[serde(rename = "darkMode", skip_serializing_if = "Option::is_none")]
    pub dark_mode: Option<bool>,
    #[serde(rename = "formatDateOrder", skip_serializing_if = "Option::is_none")]
    pub format_date_order: Option<models::TypesCivilDateOrder>,
    #[serde(rename = "formatDateSeparator", skip_serializing_if = "Option::is_none")]
    pub format_date_separator: Option<models::TypesCivilDateSeparator>,
    #[serde(rename = "formatTime24", skip_serializing_if = "Option::is_none")]
    pub format_time24: Option<bool>,
    #[serde(rename = "formatWeek8601", skip_serializing_if = "Option::is_none")]
    pub format_week8601: Option<bool>,
    #[serde(rename = "hideCalendarBudgetRecurrences", skip_serializing_if = "Option::is_none")]
    pub hide_calendar_budget_recurrences: Option<bool>,
    #[serde(rename = "hideCalendarCookMealPlans", skip_serializing_if = "Option::is_none")]
    pub hide_calendar_cook_meal_plans: Option<bool>,
    #[serde(rename = "hideCalendarEvents", skip_serializing_if = "Option::is_none")]
    pub hide_calendar_events: Option<bool>,
    #[serde(rename = "hideCalendarHealthLogs", skip_serializing_if = "Option::is_none")]
    pub hide_calendar_health_logs: Option<Vec<String>>,
    #[serde(rename = "hideCalendarPlanTasks", skip_serializing_if = "Option::is_none")]
    pub hide_calendar_plan_tasks: Option<bool>,
    #[serde(rename = "hideComponents", skip_serializing_if = "Option::is_none")]
    pub hide_components: Option<Vec<String>>,
    #[serde(rename = "ignoreDeviceAgenda", skip_serializing_if = "Option::is_none")]
    pub ignore_device_agenda: Option<bool>,
    #[serde(rename = "ignoreDeviceCalendarEvent", skip_serializing_if = "Option::is_none")]
    pub ignore_device_calendar_event: Option<bool>,
    #[serde(rename = "ignoreDevicePlanTask", skip_serializing_if = "Option::is_none")]
    pub ignore_device_plan_task: Option<bool>,
    #[serde(rename = "ignoreEmailAgenda", skip_serializing_if = "Option::is_none")]
    pub ignore_email_agenda: Option<bool>,
    #[serde(rename = "ignoreEmailCalendarEvent", skip_serializing_if = "Option::is_none")]
    pub ignore_email_calendar_event: Option<bool>,
    #[serde(rename = "ignoreEmailPlanTask", skip_serializing_if = "Option::is_none")]
    pub ignore_email_plan_task: Option<bool>,
    #[serde(rename = "notificationsHouseholds", skip_serializing_if = "Option::is_none")]
    pub notifications_households: Option<Vec<models::ModelsAuthAccountPreferencesNotificationsHousehold>>,
    #[serde(rename = "showCalendarPlanTasksCompleted", skip_serializing_if = "Option::is_none")]
    pub show_calendar_plan_tasks_completed: Option<bool>,
}

impl ModelsAuthAccountPreferences {
    pub fn new() -> ModelsAuthAccountPreferences {
        ModelsAuthAccountPreferences {
            color_accent: None,
            color_negative: None,
            color_positive: None,
            color_primary: None,
            color_secondary: None,
            colors: None,
            dark_mode: None,
            format_date_order: None,
            format_date_separator: None,
            format_time24: None,
            format_week8601: None,
            hide_calendar_budget_recurrences: None,
            hide_calendar_cook_meal_plans: None,
            hide_calendar_events: None,
            hide_calendar_health_logs: None,
            hide_calendar_plan_tasks: None,
            hide_components: None,
            ignore_device_agenda: None,
            ignore_device_calendar_event: None,
            ignore_device_plan_task: None,
            ignore_email_agenda: None,
            ignore_email_calendar_event: None,
            ignore_email_plan_task: None,
            notifications_households: None,
            show_calendar_plan_tasks_completed: None,
        }
    }
}

