/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OidcClientIssuer {
    /// OPTIONAL AuthURL is the endpoint for OAuth.  Can be discovered from OIDCIssuerURL.
    #[serde(rename = "authURL", skip_serializing_if = "Option::is_none")]
    pub auth_url: Option<String>,
    /// OPTIONAL AuthURLParams to send with OAuth.
    #[serde(rename = "authURLParams", skip_serializing_if = "Option::is_none")]
    pub auth_url_params: Option<std::collections::HashMap<String, String>>,
    /// OPTIONAL CA certificate to use with requests.
    #[serde(rename = "caCertificateBase64", skip_serializing_if = "Option::is_none")]
    pub ca_certificate_base64: Option<String>,
    /// REQUIRED ClientID is the ID shared with clients for OAuth requests.
    #[serde(rename = "clientID", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// REQUIRED ClientSecret is used to retrieve tokens from OAuth responses.
    #[serde(rename = "clientSecret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    /// OPTIONAL Custom claims to be added to JWT.
    #[serde(rename = "clientSecretJWTClaimsCustom", skip_serializing_if = "Option::is_none")]
    pub client_secret_jwt_claims_custom: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// OPTIONAL Registered claims to be added to JWT.
    #[serde(rename = "clientSecretJWTClaimsReg", skip_serializing_if = "Option::is_none")]
    pub client_secret_jwt_claims_reg: Option<Box<models::JwtRegisteredClaims>>,
    /// OPTIONAL Key that can be used to generate a JWT for the clientSecret.
    #[serde(rename = "clientSecretJWTKey", skip_serializing_if = "Option::is_none")]
    pub client_secret_jwt_key: Option<Box<models::CryptolibKeyCryptolibKeyProviderPrivate>>,
    /// OPTIONAL CodeChallengeMethodsSupported is an optional list of supported.  Can be discovered from OIDCIssuerURL
    #[serde(rename = "codeChallengeMethodsSupported", skip_serializing_if = "Option::is_none")]
    pub code_challenge_methods_supported: Option<Vec<String>>,
    /// OPTIONAL Display name of the ClientIssuer.
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// A list of filters to test the returned token with.
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<Vec<models::TypesFilter>>,
    /// OPTIONAL Icon of the ClientIssuer.
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// OPTIONAL Issuer URL of the Issuer.  Must match aud for token.  Can be discovered from OIDCIssuerURL.
    #[serde(rename = "issuerURL", skip_serializing_if = "Option::is_none")]
    pub issuer_url: Option<String>,
    /// OPTIONAL List of public keys for the Issuer.  Can be discovered from JWKSURI
    #[serde(rename = "jwksKeys", skip_serializing_if = "Option::is_none")]
    pub jwks_keys: Option<Vec<models::CryptolibKeyCryptolibKeyProviderPublic>>,
    /// OPTIONAL URL to retrieve JWKSKeys.  Can be discovered from OIDCIssuerURL
    #[serde(rename = "jwksURI", skip_serializing_if = "Option::is_none")]
    pub jwks_uri: Option<String>,
    /// OPTIONAL URL to retrieve issuer configurations.
    #[serde(rename = "oidcIssuerURL", skip_serializing_if = "Option::is_none")]
    pub oidc_issuer_url: Option<String>,
    /// OPTIONAL List of scopes to request.  Should include openid for OIDC issuers.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    /// OPTIONAL URL to retrieve token from.  Can be discovered from OIDCIssuerURL.
    #[serde(rename = "tokenURL", skip_serializing_if = "Option::is_none")]
    pub token_url: Option<String>,
    /// OPTIONAL URL to retrieve user info.  Can be discovered from OIDCIssuerURL.
    #[serde(rename = "userInfoEndpoint", skip_serializing_if = "Option::is_none")]
    pub user_info_endpoint: Option<String>,
}

impl OidcClientIssuer {
    pub fn new() -> OidcClientIssuer {
        OidcClientIssuer {
            auth_url: None,
            auth_url_params: None,
            ca_certificate_base64: None,
            client_id: None,
            client_secret: None,
            client_secret_jwt_claims_custom: None,
            client_secret_jwt_claims_reg: None,
            client_secret_jwt_key: None,
            code_challenge_methods_supported: None,
            display_name: None,
            filters: None,
            icon: None,
            issuer_url: None,
            jwks_keys: None,
            jwks_uri: None,
            oidc_issuer_url: None,
            scopes: None,
            token_url: None,
            user_info_endpoint: None,
        }
    }
}

