/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypesUserAgent {
    #[serde(rename = "unknown")]
    UserAgentUnknown,
    #[serde(rename = "api")]
    UserAgentAPI,
    #[serde(rename = "android")]
    UserAgentAndroid,
    #[serde(rename = "chrome")]
    UserAgentChrome,
    #[serde(rename = "edge")]
    UserAgentEdge,
    #[serde(rename = "firefox")]
    UserAgentFirefox,
    #[serde(rename = "ios")]
    UserAgentIOS,
    #[serde(rename = "safari")]
    UserAgentSafari,

}

impl std::fmt::Display for TypesUserAgent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserAgentUnknown => write!(f, "unknown"),
            Self::UserAgentAPI => write!(f, "api"),
            Self::UserAgentAndroid => write!(f, "android"),
            Self::UserAgentChrome => write!(f, "chrome"),
            Self::UserAgentEdge => write!(f, "edge"),
            Self::UserAgentFirefox => write!(f, "firefox"),
            Self::UserAgentIOS => write!(f, "ios"),
            Self::UserAgentSafari => write!(f, "safari"),
        }
    }
}

impl Default for TypesUserAgent {
    fn default() -> TypesUserAgent {
        Self::UserAgentUnknown
    }
}

