/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Serialize_repr,Deserialize_repr};
/// 
#[repr(i64)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr)]
pub enum TypesCurrency {
    CurrencyUSD = 0,
    CurrencyGBP = 1,
    CurrencyEUR = 2,
    CurrencyCAD = 3,
    CurrencyINR = 4,
    CurrencyJPY = 5,
    CurrencyKRW = 6,
    CurrencyMXN = 7,
    CurrencyRUB = 8,
    CurrencyCHF = 9,
    CurrencyZAR = 10,
    CurrencyAUD = 11,
    CurrencyBRL = 12,
    CurrencySEK = 13,
    CurrencyAED = 14,
    CurrencyDKK = 15,
    CurrencyTWD = 16,

}

impl std::fmt::Display for TypesCurrency {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", match self {
            Self::CurrencyUSD => "0",
            Self::CurrencyGBP => "1",
            Self::CurrencyEUR => "2",
            Self::CurrencyCAD => "3",
            Self::CurrencyINR => "4",
            Self::CurrencyJPY => "5",
            Self::CurrencyKRW => "6",
            Self::CurrencyMXN => "7",
            Self::CurrencyRUB => "8",
            Self::CurrencyCHF => "9",
            Self::CurrencyZAR => "10",
            Self::CurrencyAUD => "11",
            Self::CurrencyBRL => "12",
            Self::CurrencySEK => "13",
            Self::CurrencyAED => "14",
            Self::CurrencyDKK => "15",
            Self::CurrencyTWD => "16",
        })
    }
}
impl Default for TypesCurrency {
    fn default() -> TypesCurrency {
        Self::CurrencyUSD
    }
}

