/*
 * Homechart
 *
 * _The API to your family's mission control.  Manage budgets, calendars, tasks, recipes, notes, and more._  # API Responses  All API responses are wrapped within a **httplib.JSONResponse.  Users should always check if the `error` property is defined in the response and handle the error accordingly.  Homechart uses these `error.code` values:  - `400`: Bad request, ensure the request contains valid/required values. - `401`: Unauthorized, request is missing valid authorization credentials. - `402`: Payment required, your Homechart subscription is expired. - `403`: Forbidden, missing permissions to perform action. - `404`: Not found, the item was not found. - `409`: Conflict, the resource already exists. - `429`: Too many requests, you are being rate limited.  If the `data` property is defined, the `data.type` property specifies the underlying type of the `data.value`.  `data.value` **will always be an array**, even if it just contains one item.  This helps clients avoid having to figure out if it's an array or a single item.  # Getting Started  To authorize your API responses, generate an API key via the [Homechart UI (Settings > Sessions)](/settings/sessions) or the [Homechart API POST /auth/sessions operation](#operations-AuthSession-post_auth_sessions). 
 *
 * The version of the OpenAPI document: v2025.12.29+f7c74cd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TypesDuration {
    #[serde(rename = "-9223372036854775808")]
    DurationDay,
    #[serde(rename = "9223372036854775807")]
    DurationHour,
    #[serde(rename = "1")]
    DurationMinute,
    #[serde(rename = "1000")]
    DurationSecond,
    #[serde(rename = "1000000")]
    Variant1000000,
    #[serde(rename = "1000000000")]
    Variant1000000000,
    #[serde(rename = "60000000000")]
    Variant60000000000,
    #[serde(rename = "3600000000000")]
    Variant3600000000000,
    #[serde(rename = "1")]
    Variant12,
    #[serde(rename = "1000")]
    Variant10002,
    #[serde(rename = "1000000")]
    Variant10000002,
    #[serde(rename = "1000000000")]
    Variant10000000002,
    #[serde(rename = "60000000000")]
    Variant600000000002,
    #[serde(rename = "3600000000000")]
    Variant36000000000002,
    #[serde(rename = "86400000000000")]
    Variant86400000000000,
    #[serde(rename = "3600000000000")]
    Variant36000000000003,
    #[serde(rename = "60000000000")]
    Variant600000000003,
    #[serde(rename = "1000000000")]
    Variant10000000003,

}

impl std::fmt::Display for TypesDuration {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DurationDay => write!(f, "-9223372036854775808"),
            Self::DurationHour => write!(f, "9223372036854775807"),
            Self::DurationMinute => write!(f, "1"),
            Self::DurationSecond => write!(f, "1000"),
            Self::Variant1000000 => write!(f, "1000000"),
            Self::Variant1000000000 => write!(f, "1000000000"),
            Self::Variant60000000000 => write!(f, "60000000000"),
            Self::Variant3600000000000 => write!(f, "3600000000000"),
            Self::Variant12 => write!(f, "1"),
            Self::Variant10002 => write!(f, "1000"),
            Self::Variant10000002 => write!(f, "1000000"),
            Self::Variant10000000002 => write!(f, "1000000000"),
            Self::Variant600000000002 => write!(f, "60000000000"),
            Self::Variant36000000000002 => write!(f, "3600000000000"),
            Self::Variant86400000000000 => write!(f, "86400000000000"),
            Self::Variant36000000000003 => write!(f, "3600000000000"),
            Self::Variant600000000003 => write!(f, "60000000000"),
            Self::Variant10000000003 => write!(f, "1000000000"),
        }
    }
}

impl Default for TypesDuration {
    fn default() -> TypesDuration {
        Self::DurationDay
    }
}

